[package]
name = "bc-crypto"
version = "0.1.1"
edition = "2021"
description = "Gordian Envelope for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-crypto-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["cryptography"]
documentation = "https://docs.rs/bc-crypto"

[dependencies]
sha2 = "0.10.6"
hmac = "0.12.1"
pbkdf2 = "0.12.1"
hkdf = "0.12.3"
rand = "0.8.5"
getrandom = "0.2.9"
lazy_static = "1.4.0"
crc32fast = "1.3.2"
rand_xoshiro = "0.6.0"
num-traits = "0.2.15"
chacha20poly1305 = "0.10.1"
#k256 = {version = "0.13.1", default-features = false, features = ["ecdsa", "arithmetic"]}
secp256k1 = "0.27.0"
x25519-dalek = {version = "2.0.0-rc.2", features = ["static_secrets"]}

[dev-dependencies]
hex-literal = "0.4.1"
hex = "0.4.3"
version-sync = "0.9"
