[package]
name = "bc-crypto"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"
description = "Gordian Envelope for Rust."
authors = ["Blockchain Commons"]
keywords = ["cryptography"]
repository = "https://github.com/BlockchainCommons/bc-crypto-rust"
readme = "README.md"
categories = ["cryptography"]

[dependencies]
sha2 = "0.10.6"
rand = "0.8.5"
getrandom = "0.2.9"
lazy_static = "1.4.0"
crc32fast = "1.3.2"
rand_xoshiro = "0.6.0"
num-traits = "0.2.15"

[dev-dependencies]
hex-literal = "0.4.1"
hex = "0.4.3"
